name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
          deno install
          deno check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
          deno fmt --check
          deno lint
