name: Release

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - run: npm install

      - name: Package the extension
        run: npx vsce package

      # - name: Publish to marketplace
      #   run: npx vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: GitHub Release
        run: |
          gh release create v$(cat package.json | jq -r '.version') --generate-notes *.vsix
        env:
          GH_TOKEN: ${{ github.token }}
